<?php namespace Paolooo\Test;

trait VarTrait
{
    public function getDbParams()
    {
        return [
            'read' => [
                'database' => 'cqrs_read_db',
                'username' => 'paolo',
            ],
            'driver'   => 'pdo_sqlite',
            'username' => 'root',
            'password' => '',
            'database' => 'forge',
            'host'     => 'localhost',
        ];
    }

    public function getDoctrineParams()
    {
        return [
            'mappingDir' => 'examples/Acme/Domain/Model/Entity',
            'proxyDir'   => 'examples/Acme/Domain/Model/Entity/Proxy',
            'proxyNS'    => 'Acme\Domain\Model\Entity\Proxy',
            'proxyAutogenerated' => false,

            'read' => [
                'mappingDir' => 'examples/Acme/Read/Entity',
                'proxyDir'   => 'examples/Acme/Read/Entity/Proxy',
                'proxyNS'    => 'Acme\Read\Entity\Proxy',
                'proxyAutogenerated' => false,
            ],

            'eventstore' => [
                'mappingDir' => 'examples/Acme/EventStore/Entity',
                'proxyDir'   => 'examples/Acme/EventStore/Entity/Proxy',
                'proxyNS'    => 'Acme\EventStore\Entity\Proxy',
                'proxyAutogenerated' => false,
            ]
        ];
    }

}

