<?php

return [

    /*
    |----------------------------------------------------
    | Default Config
    |----------------------------------------------------
    */

    'mappingDir' => env('DOCTRINE_MAPPING_DIR'),
    'proxyDir' => env('DOCTRINE_PROXY_DIR'),
    'proxyNS' => env('DOCTRINE_PROXY_NAMESPACE'),
    'proxyAutogenerated' => env('DOCTRINE_PROXY_AUTOGENERATED'),

    /*
    |----------------------------------------------------
    | (CQRS) Read config
    |----------------------------------------------------
    */

    'read' => [
        'mappingDir' => env('READ_DOCTRINE_MAPPING_DIR'),
        'proxyDir' => env('READ_DOCTRINE_PROXY_DIR'),
        'proxyNS' => env('READ_DOCTRINE_PROXY_NAMESPACE'),
        'proxyAutogenerated' => env('READ_DOCTRINE_PROXY_AUTOGENERATED'),
    ],

    /*
    |----------------------------------------------------
    | EventStore
    |----------------------------------------------------
    */

    'eventstore' => [
        'mappingDir' => env('EVENTSTORE_DOCTRINE_MAPPING_DIR'),
        'proxyDir' => env('EVENTSTORE_DOCTRINE_PROXY_DIR'),
        'proxyNS' => env('EVENTSTORE_DOCTRINE_PROXY_NAMESPACE'),
        'proxyAutogenerated' => env('EVENTSTORE_DOCTRINE_PROXY_AUTOGENERATED'),
    ]
];
