<?php namespace Paolooo\LaravelDoctrine;

use Doctrine\ORM\Configuration;

class ConfigurationFactory
{
    protected $config;
    protected $cache;
    protected $mappingDir;
    protected $proxyDir;
    protected $proxyNS;

    public function __construct(
        $cache,
        $mappingDir,
        $proxyDir,
        $proxyNS,
        $proxyAutogenerated,
        Configuration $config = null
    ) {
        $this->cache = $cache;
        $this->mappingDir = $mappingDir;
        $this->proxyDir = $proxyDir;
        $this->proxyNS = $proxyNS;
        $this->proxyAutogenerated = !!$proxyAutogenerated;

        $this->setConfiguration($config);
    }

    /**
     * Set or instantiate Configuration
     */
    protected function setConfiguration(Configuration $config=null)
    {
        $this->config = (!empty($config)) ? $config : new Configuration;
    }

    /**
     * Make configuration
     */
    public function make()
    {
        $this->config->setMetadataCacheImpl($this->cache);
        $driverImpl = $this->config->newDefaultAnnotationDriver($this->mappingDir);
        $this->config->setMetadataDriverImpl($driverImpl);
        $this->config->setQueryCacheImpl($this->cache);
        $this->config->setProxyDir($this->proxyDir);
        $this->config->setProxyNamespace($this->proxyNS);
        $this->config->setAutoGenerateProxyClasses($this->proxyAutogenerated);

        return $this->config;
    }
}

